# Generated by Django 5.2.9 on 2025-12-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userweather',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='userweather',
            name='condition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
