# Generated by Django 5.2.9 on 2025-12-15 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_rename_submitted_at_userweather_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userweather',
            old_name='city_name',
            new_name='city',
        ),
    ]
