# Generated by Django 5.2.9 on 2025-12-15 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_rename_city_name_userweather_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userweather',
            old_name='created_at',
            new_name='submitted_at',
        ),
    ]
