# Generated by Django 5.2.9 on 2025-12-15 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soilrecommendation',
            name='farmer',
        ),
    ]
